
services:

  db:
    image: postgres:14-alpine
    container_name: postgres-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_catalog

    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=pg_stat_statements",
        "-c",
        "pg_stat_statements.track=all"
      ]

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7-alpine
    container_name: redis-cache

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-1:
    build: ./server
    container_name: app-1

    ports:
      - "8001:8000"

    env_file:
      - .env.example

    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-2:
    build: ./server
    container_name: app-2

    ports:
      - "8002:8000"

    env_file:
      - .env.example

    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: frontend

    ports:
      - "3000:3000"

    depends_on:
      - app-1
      - app-2

volumes:
  postgres_data: